/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * swagger-ton
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}


/**
 * GenerateValueApi - fetch parameter creator
 * @export
 */
export const GenerateValueApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary This deletes the value
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: number, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling _delete.');
            }
            const localVarPath = `/GenerateValue/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Concatenates the params together
         * @param {number} id Id Param
         * @param {string} [value1] Val1 Param
         * @param {string} [value2] Val2 Param
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: number, value1?: string, value2?: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling get.');
            }
            const localVarPath = `/GenerateValue/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (value1 !== undefined) {
                localVarQueryParameter['value1'] = value1;
            }

            if (value2 !== undefined) {
                localVarQueryParameter['value2'] = value2;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Submit a value
         * @param {string} [value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        post(value?: string, options: any = {}): FetchArgs {
            const localVarPath = `/GenerateValue`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"string" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(value || {}) : (value || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a value
         * @param {number} id Id of value
         * @param {string} [value] The value to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        put(id: number, value?: string, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling put.');
            }
            const localVarPath = `/GenerateValue/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"string" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(value || {}) : (value || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GenerateValueApi - functional programming interface
 * @export
 */
export const GenerateValueApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary This deletes the value
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: number, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = GenerateValueApiFetchParamCreator(configuration)._delete(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Concatenates the params together
         * @param {number} id Id Param
         * @param {string} [value1] Val1 Param
         * @param {string} [value2] Val2 Param
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: number, value1?: string, value2?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = GenerateValueApiFetchParamCreator(configuration).get(id, value1, value2, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Submit a value
         * @param {string} [value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        post(value?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = GenerateValueApiFetchParamCreator(configuration).post(value, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Update a value
         * @param {number} id Id of value
         * @param {string} [value] The value to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        put(id: number, value?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = GenerateValueApiFetchParamCreator(configuration).put(id, value, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * GenerateValueApi - factory interface
 * @export
 */
export const GenerateValueApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary This deletes the value
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        _delete(id: number, options?: any) {
            return GenerateValueApiFp(configuration)._delete(id, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Concatenates the params together
         * @param {number} id Id Param
         * @param {string} [value1] Val1 Param
         * @param {string} [value2] Val2 Param
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(id: number, value1?: string, value2?: string, options?: any) {
            return GenerateValueApiFp(configuration).get(id, value1, value2, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Submit a value
         * @param {string} [value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        post(value?: string, options?: any) {
            return GenerateValueApiFp(configuration).post(value, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Update a value
         * @param {number} id Id of value
         * @param {string} [value] The value to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        put(id: number, value?: string, options?: any) {
            return GenerateValueApiFp(configuration).put(id, value, options)(fetch, basePath);
        },
    };
};

/**
 * GenerateValueApi - object-oriented interface
 * @export
 * @class GenerateValueApi
 * @extends {BaseAPI}
 */
export class GenerateValueApi extends BaseAPI {
    /**
     * 
     * @summary This deletes the value
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenerateValueApi
     */
    public _delete(id: number, options?: any) {
        return GenerateValueApiFp(this.configuration)._delete(id, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Concatenates the params together
     * @param {number} id Id Param
     * @param {string} [value1] Val1 Param
     * @param {string} [value2] Val2 Param
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenerateValueApi
     */
    public get(id: number, value1?: string, value2?: string, options?: any) {
        return GenerateValueApiFp(this.configuration).get(id, value1, value2, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Submit a value
     * @param {string} [value] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenerateValueApi
     */
    public post(value?: string, options?: any) {
        return GenerateValueApiFp(this.configuration).post(value, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Update a value
     * @param {number} id Id of value
     * @param {string} [value] The value to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GenerateValueApi
     */
    public put(id: number, value?: string, options?: any) {
        return GenerateValueApiFp(this.configuration).put(id, value, options)(this.fetch, this.basePath);
    }

}

